stages:
  download:
    cmd: Rscript stages/1_download.R
    deps:
      - stages/1_download.R
    outs:
      - brick/dsstox_identifiers.parquet
  api_EPA:
    cmd: python stages/2_API_EPA.py
    deps:
      - stages/2_API_EPA.py
    outs:
      - brick/chemical_lists.parquet
      - brick/cchemicals_by_list.parquet
