stages:
  download:
    cmd: bash stages/1_download.sh 
    deps:
      - stages/1_download.sh
      - stages/check_listofchemicals.py
    outs:
      - download
  build:
    cmd: bash stages/2_build.sh 
    deps:
      - stages/2_build.sh
      - stages/csv2parquet.py
      - download
    outs:
      - brick
