stages:
  download_data:
    cmd: bash stages/1_download.sh 
    deps:
      - stages/1_download.sh
      - stages/check_listofchemicals.py
    outs:
      - download/
      - download/DSSTox_Identifiers.csv
      - download/list_chemicals/
  build_data:
    cmd: bash stages/2_build.sh 
    deps:
      - download/
      - download/DSSTox_Identifiers.csv
      - download/list_chemicals/
    outs:
      - brick/

