stages:
  download:
    cmd: Rscript stages/1_download.R
    deps:
      - stages/1_download.R
      - https://clowder.edap-cluster.com/datasets/61147fefe4b0856fdc65639b#folderId=61148181e4b0856fdc65643f&page=0
    outs:
      - brick/dsstox_identifiers.parquet
